import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';

const deliveries = [
  { id: 'D-1042', shop: 'FreshMart Sandton', customer: 'Lerato M.', address: '18 Main Road, Sandton', pay: 42, distance: '3.2 km', items: 'Milk, bread, eggs and apples' },
  { id: 'D-1045', shop: 'Urban Grocer Rosebank', customer: 'Sipho N.', address: '7 Rose Street, Rosebank', pay: 38, distance: '2.6 km', items: 'Rice, chicken, tomatoes and juice' },
];

export default function DriverScreen() {
  const [online, setOnline] = useState(true);
  const [active, setActive] = useState<string | null>(null);
  const [stage, setStage] = useState<'travel' | 'shopping' | 'delivery'>('travel');
  const job = deliveries.find((item) => item.id === active);

  return <SafeAreaView style={styles.screen}>
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.top}><Pressable onPress={() => router.replace('/(tabs)/menu')} style={styles.back}><ThemedText style={styles.backText}>‹</ThemedText></Pressable><View><ThemedText style={styles.eyebrow}>DRIVER MODE</ThemedText><ThemedText style={styles.title}>Shopper dashboard</ThemedText></View></View>
      <View style={[styles.status, online ? styles.online : styles.offline]}><View><ThemedText style={styles.statusTitle}>{online ? 'You are online' : 'You are offline'}</ThemedText><ThemedText style={styles.statusSub}>{online ? 'New shopping requests are visible' : 'Go online to receive requests'}</ThemedText></View><Pressable onPress={() => setOnline((value) => !value)} style={[styles.toggle, online && styles.toggleOn]}><View style={[styles.knob, online && styles.knobOn]} /></Pressable></View>
      <View style={styles.stats}><View style={styles.stat}><ThemedText style={styles.statValue}>R284</ThemedText><ThemedText style={styles.statLabel}>Today</ThemedText></View><View style={styles.stat}><ThemedText style={styles.statValue}>7</ThemedText><ThemedText style={styles.statLabel}>Orders</ThemedText></View><View style={styles.stat}><ThemedText style={styles.statValue}>4.9</ThemedText><ThemedText style={styles.statLabel}>Rating</ThemedText></View></View>
      {job ? <View style={styles.activeCard}><ThemedText style={styles.sectionTitle}>Active shopping order</ThemedText><ThemedText style={styles.jobShop}>{job.shop} → {job.customer}</ThemedText><ThemedText style={styles.address}>{job.address}</ThemedText><View style={styles.shoppingList}><ThemedText style={styles.listLabel}>SHOPPING LIST</ThemedText><ThemedText style={styles.listItems}>{job.items}</ThemedText></View><View style={styles.progress}><View style={[styles.step, styles.stepDone]} /><View style={[styles.line, stage !== 'travel' && styles.lineDone]} /><View style={[styles.step, stage !== 'travel' && styles.stepDone]} /><View style={[styles.line, stage === 'delivery' && styles.lineDone]} /><View style={[styles.step, stage === 'delivery' && styles.stepDone]} /></View><View style={styles.stageLabels}><ThemedText style={styles.stageText}>Shop</ThemedText><ThemedText style={styles.stageText}>Buy</ThemedText><ThemedText style={styles.stageText}>Deliver</ThemedText></View><Pressable onPress={() => stage === 'travel' ? setStage('shopping') : stage === 'shopping' ? setStage('delivery') : setActive(null)} style={styles.primary}><ThemedText style={styles.primaryText}>{stage === 'travel' ? 'I arrived at the shop' : stage === 'shopping' ? 'Items purchased' : 'Confirm delivered'}</ThemedText></Pressable></View> : <><ThemedText style={styles.sectionTitle}>Available shopping requests</ThemedText>{online && deliveries.map((item) => <View key={item.id} style={styles.job}><View style={styles.jobTop}><View><ThemedText style={styles.jobShop}>{item.shop}</ThemedText><ThemedText style={styles.address}>{item.distance} • {item.items}</ThemedText></View><ThemedText style={styles.pay}>R{item.pay}</ThemedText></View><Pressable onPress={() => { setActive(item.id); setStage('travel'); }} style={styles.accept}><ThemedText style={styles.acceptText}>Accept shopping request</ThemedText></Pressable></View>)}</>}
      <Pressable onPress={() => router.push('/profile')} style={styles.switch}><ThemedText style={styles.switchText}>Switch account mode</ThemedText></Pressable>
    </ScrollView>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:'#F6F8FC'},content:{padding:24,gap:20},top:{flexDirection:'row',alignItems:'center',gap:14},back:{width:42,height:42,borderRadius:14,backgroundColor:'#FFF',alignItems:'center',justifyContent:'center'},backText:{fontSize:32,lineHeight:34,color:'#182036'},eyebrow:{fontSize:10,fontWeight:800,letterSpacing:1.2,color:'#2563EB'},title:{fontSize:25,fontWeight:800,color:'#182036'},status:{borderRadius:22,padding:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},online:{backgroundColor:'#E9F9F0'},offline:{backgroundColor:'#EEF0F4'},statusTitle:{fontSize:16,fontWeight:800,color:'#182036'},statusSub:{fontSize:11,color:'#6B7280',marginTop:3},toggle:{width:48,height:28,borderRadius:14,backgroundColor:'#AAB0BC',padding:3},toggleOn:{backgroundColor:'#16A060'},knob:{width:22,height:22,borderRadius:11,backgroundColor:'#FFF'},knobOn:{alignSelf:'flex-end'},stats:{flexDirection:'row',gap:10},stat:{flex:1,backgroundColor:'#FFF',borderRadius:18,padding:15},statValue:{fontSize:19,fontWeight:800,color:'#182036'},statLabel:{fontSize:11,color:'#767B8C',marginTop:3},sectionTitle:{fontSize:19,fontWeight:800,color:'#182036'},job:{backgroundColor:'#FFF',borderRadius:20,padding:17,gap:15},jobTop:{flexDirection:'row',justifyContent:'space-between',gap:10},jobShop:{fontSize:15,fontWeight:800,color:'#182036'},address:{fontSize:11,color:'#73798B',marginTop:4},pay:{fontSize:17,fontWeight:800,color:'#16A060'},accept:{borderRadius:13,backgroundColor:'#2563EB',padding:13,alignItems:'center'},acceptText:{color:'#FFF',fontSize:13,fontWeight:800},activeCard:{backgroundColor:'#FFF',borderRadius:22,padding:20,gap:14},shoppingList:{backgroundColor:'#F4F6FA',borderRadius:14,padding:14},listLabel:{fontSize:9,fontWeight:800,letterSpacing:1,color:'#73798B'},listItems:{fontSize:13,fontWeight:700,color:'#182036',marginTop:5},progress:{flexDirection:'row',alignItems:'center',paddingTop:8},stageLabels:{flexDirection:'row',justifyContent:'space-between'},stageText:{fontSize:10,fontWeight:700,color:'#73798B'},step:{width:14,height:14,borderRadius:7,backgroundColor:'#D7DAE2'},stepDone:{backgroundColor:'#16A060'},line:{flex:1,height:3,backgroundColor:'#D7DAE2'},lineDone:{backgroundColor:'#16A060'},primary:{backgroundColor:'#16A060',borderRadius:14,padding:15,alignItems:'center'},primaryText:{color:'#FFF',fontWeight:800},switch:{padding:14,alignItems:'center'},switchText:{color:'#2563EB',fontSize:13,fontWeight:800},
});
